### 회원가입
POST http://localhost:8080/users
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}",
  "name": "{{name}}",
  "manager": "{{manager}}",
  "managerToken": "{{managerToken}}"
}

### 로그인
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "username":"{{username}}",
  "password":"{{password}}"
}

> {%
  client.log(response.headers.valueOf("Authorization"));
  client.log(response.headers.valueOf("Refresh_token"));
  client.global.set("Authorization", response.headers.valueOf("Authorization"));
  client.global.set("Refresh_token", response.headers.valueOf("Refresh_token"));
%}

### 보드 생성
POST http://localhost:8080/boards
Authorization: {{Authorization}}
Content-Type: application/json

{
  "title": "testBoard",
  "description": "설명"
}

### 보드 수정
PATCH http://localhost:8080/boards/1
Authorization: {{Authorization}}
Content-Type: application/json

{
  "title": "수정된 제목",
  "description": "수정된설명"
}

### 보드 삭제
DELETE http://localhost:8080/boards/4
Authorization: {{Authorization}}

### 모든 보드 조회
GET http://localhost:8080/boards
Authorization: {{Authorization}}

### 단일 보드 조회
GET http://localhost:8080/boards/1
Authorization: {{Authorization}}

### 보드 초대
POST http://localhost:8080/boards/1/invite
Authorization: {{Authorization}}
Content-Type: application/json

{
  "userId" : "2"
}